labware:
  plate:
    load_name: sbs_96_wellplate
    name: cub_deck_example_plate
    model_name: cub_deck_example_plate
    calibration:
      a1:
        x: 70.0
        y: 45.0
        z: 25.0
      a2:
        x: 79.0
        y: 45.0
        z: 25.0
    x_offset: 9.0
    y_offset: 9.0
