labware:
  plate:
    type: well_plate
    name: asmi_96_well_deck_origin
    model_name: asmi_96_well_deck_origin
    rows: 8
    columns: 12
    length: 127.76
    width: 85.47
    height: 14.35
    well_depth: 10.67
    calibration:
      a1:
        x: 347
        y: 42
        z: 30
      a2:
        x: 338
        y: 42
        z: 30
    x_offset: 9
    y_offset: 9
    capacity_ul: 200
    working_volume_ul: 150
